// ESLint flat configuration for the Customer Master frontend.
//
// Correctness rules only, no formatting rules. No type-aware preset
// (`recommendedTypeChecked`): linting needs no TypeScript program and stays
// fast, and `tsc -b` in `npm run build` enforces `strict` and
// `noUncheckedIndexedAccess`.
import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig([
  // src/api/schema.d.ts is generated by `npm run gen:api` and compared byte for
  // byte by `git diff --exit-code`, so no lint run (and no --fix) touches it.
  globalIgnores(['dist', 'coverage', 'src/api/schema.d.ts']),

  {
    name: 'customer-master/typescript',
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    rules: {
      // A leading underscore marks a parameter or variable that is
      // intentionally unused, such as a positional callback argument.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  {
    name: 'customer-master/node-tooling',
    files: ['vite.config.ts', 'eslint.config.js'],
    languageOptions: {
      globals: globals.node,
    },
  },
]);
