package com.democorp.customermaster.repository;

import com.democorp.customermaster.domain.Customer;
import com.democorp.customermaster.domain.CustomerId;
import org.springframework.data.repository.CrudRepository;

/**
 * Create, read and update access to the {@code custmast} table, as the Spring Data JDBC
 * repository of the {@link Customer} aggregate keyed by {@link CustomerId}.
 *
 * <p><b>What it replaces.</b> The three record procedures of MTNCUSTR, whose USPS variant runs
 * the same logic [USPS_Address/MTNCUSTR.SQLRPGLE:331-350,615-676]:
 * <table>
 *   <caption>Source procedure and repository method</caption>
 *   <tr><th>Source</th><th>Statement</th><th>Here</th></tr>
 *   <tr><td>{@code ReadRecd} [5250_Subfile/MTNCUSTR.SQLRPGLE:315-338]</td>
 *       <td>{@code select CUSTID, ..., CHGUSER into :CUSTMAST_ds from CUSTMAST
 *       where CUSTID = :pID}, the twelve columns of [5250_Subfile/Custmast2.sql:9-21]</td>
 *       <td>{@code findById(id)}</td></tr>
 *   <tr><td>{@code AddRecd} [5250_Subfile/MTNCUSTR.SQLRPGLE:548-566]</td>
 *       <td>{@code insert into custmast values(:CUSTMAST_ds)}</td>
 *       <td>{@code save(customer)} of a new aggregate</td></tr>
 *   <tr><td>{@code UpdateRecd} [5250_Subfile/MTNCUSTR.SQLRPGLE:567-607]</td>
 *       <td>{@code update CUSTMAST SET ... where CUSTID = :CUSTID and CHGTIME = :Orig_CHGTIME}</td>
 *       <td>{@code save(customer)} of a loaded aggregate</td></tr>
 * </table>
 * Search is not here: the keyset statement lives in {@code CustomerSearchRepository}, and id
 * allocation in {@code CustomerIdAllocator}. No delete is offered to callers either: the source
 * has none, and customers are deactivated with {@code active = 'N'}. The delete methods that
 * {@link CrudRepository} declares are inherited, but no production code calls them.
 *
 * <p><b>Declared methods.</b> None. The interface adds no query, no lock mode and no paging to
 * what {@link CrudRepository} provides, so every statement it runs is generated by Spring Data
 * JDBC from the {@code @Column} names of {@link Customer} and its embedded
 * {@code domain.Address}. Those are the V3 names ({@code custid}, {@code name}, {@code addr},
 * {@code city}, {@code state}, {@code zip}, {@code corpphone}, {@code acctmgr},
 * {@code acctphone}, {@code active}, {@code chgtime}, {@code chguser}, {@code row_version}),
 * the same names the handwritten SQL of {@code CustomerSearchRepository},
 * {@code CustomerIdAllocator} and {@code CustomerCopyWriter} uses. Identifiers are quoted in
 * lowercase, which matches the unquoted lowercase names V3 creates, and are never
 * schema-qualified: the schema comes from the connection ({@code currentSchema} and the Hikari
 * schema, both from {@code DB_SCHEMA}). The {@link CustomerId} key is bound and read as its
 * 4-character text through the converters of {@link JdbcConfig}.
 *
 * <p><b>Contract callers rely on.</b> It is Spring Data JDBC's own behaviour for an aggregate
 * whose {@code @Version} property is the wrapper {@link Long}; nothing here implements it.
 * <ul>
 *   <li><b>New aggregate.</b> {@code save(customer)} with {@code rowVersion() == null} and an id
 *       already assigned by {@code CustomerIdAllocator.next()} issues
 *       {@code INSERT INTO "custmast" ("custid", "name", ..., "row_version") VALUES (...)} with the
 *       assigned id and version 0, and returns a copy carrying version 0.</li>
 *   <li><b>Loaded aggregate.</b> {@code save(customer)} with {@code rowVersion() == v} issues
 *       {@code UPDATE "custmast" SET "name" = ..., "row_version" = v + 1
 *       WHERE "custid" = :id AND "row_version" = v} and returns a copy carrying {@code v + 1}.
 *       The version token replaces UpdateRecd's {@code CHGTIME = :Orig_CHGTIME} test, and no row
 *       lock outlives the caller's transaction.</li>
 *   <li><b>No row matched.</b> When that {@code UPDATE} changes no row, whether the version is
 *       stale or the row is gone, {@code save} throws
 *       {@link org.springframework.dao.OptimisticLockingFailureException}, which Spring Data JDBC
 *       rethrows unwrapped. It replaces UpdateRecd's {@code SQLNODATA} branch. The caller,
 *       {@code CustomerMaintenanceService.update}, re-reads with {@code findById} in the same
 *       transaction: an absent row gives 404 DEM0599, a present one 409 DEM1002 carrying the row
 *       as now stored.</li>
 *   <li><b>Other write failures.</b> Every other failure of {@code save} is wrapped in
 *       {@link org.springframework.data.relational.core.conversion.DbActionExecutionException},
 *       so callers walk the cause chain. SQLSTATE {@code 55P03} (the {@code lock_timeout} the
 *       caller set expired) or a {@link org.springframework.dao.CannotAcquireLockException}
 *       becomes {@code CustomerLockedException}, 409 DEM1001, UpdateRecd's
 *       {@code SQLROWLOCKED} branch. The SQLSTATE test is the one that matters here: Spring's
 *       PostgreSQL error codes leave {@code 55P03} uncategorized, so a lock timeout inside
 *       {@code save} arrives as a {@link org.springframework.jdbc.UncategorizedSQLException}
 *       whose {@link java.sql.SQLException} carries {@code 55P03}, not as a
 *       {@code CannotAcquireLockException}. A duplicate key
 *       ({@link org.springframework.dao.DuplicateKeyException}), possible only when a row was
 *       written outside the allocator, becomes 500 DEM9999, as {@code SQLProblem} ends
 *       AddRecd.</li>
 *   <li><b>Missing row on read.</b> {@code findById} returns an empty {@link java.util.Optional}
 *       where ReadRecd continued with {@code SQLNODATA}; the caller answers 404 DEM0599.</li>
 *   <li><b>Transactions.</b> The repository starts none beyond Spring Data's per-method
 *       defaults, which join an open transaction. Callers own the transaction, its
 *       {@code SET LOCAL lock_timeout} and the allocation guard, and keep it short; no lock is
 *       ever held across a user's think time.</li>
 * </ul>
 *
 * <p>Example, inside the caller's transaction:
 * <pre>{@code
 * Customer added = customers.save(draft.withCustId(allocator.next())
 *         .withStamp(OffsetDateTime.now(clock), "sales"));       // INSERT, version 0
 * Customer edited = customers.save(changed.withCustId(added.custId())
 *         .withRowVersion(0L)
 *         .withStamp(OffsetDateTime.now(clock), "sales"));       // UPDATE ... AND row_version = 0
 * edited.rowVersion();                                           // 1
 * customers.save(changed.withCustId(added.custId()).withRowVersion(0L));
 *                                                                // OptimisticLockingFailureException
 * }</pre>
 *
 * <p>Spring Data creates one thread-safe proxy of this interface; it holds no state.
 */
public interface CustomerRepository extends CrudRepository<Customer, CustomerId> {
}
