/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search customers by name, city and state */
        get: operations["searchCustomers"];
        put?: never;
        /** Add a customer under the next id */
        post: operations["addCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate and standardize a customer before saving */
        post: operations["reviewCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{custId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one customer */
        get: operations["getCustomer"];
        /** Change a customer at the version read */
        put: operations["updateCustomer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Message catalog keyed by message id */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signed-in user and roles */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** USA states, optionally filtered by name */
        get: operations["listStates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerFields: {
            acctMgr?: string | null;
            acctPhone?: string | null;
            active?: string | null;
            addr?: string | null;
            city?: string | null;
            corpPhone?: string | null;
            name?: string | null;
            state?: string | null;
            zip?: string | null;
        };
        CustomerResponse: {
            acctMgr: string;
            acctPhone: string;
            active: string;
            addr: string;
            /** Format: date-time */
            chgTime: string | null;
            chgUser: string;
            city: string;
            corpPhone: string;
            custId: string;
            name: string;
            state: string;
            /** Format: int64 */
            version: number;
            zip: string;
        };
        CustomerSummaryResponse: {
            active: string;
            city: string;
            custId: string;
            name: string;
            state: string;
            zip5: string;
        };
        CustomerUpdateRequest: {
            acctMgr?: string | null;
            acctPhone?: string | null;
            active?: string | null;
            addr?: string | null;
            city?: string | null;
            corpPhone?: string | null;
            name?: string | null;
            state?: string | null;
            /** Format: int64 */
            version: number;
            zip?: string | null;
        };
        /** @description One field at fault in a problem's errors */
        FieldError: {
            /**
             * @description The catalog key
             * @example DEM0502
             */
            code: string;
            /**
             * @description The request body's JSON property (name, addr, city, state, zip, corpPhone, acctMgr, acctPhone, active; version on update; purpose on review) or the path or query parameter (custId; name, city, state, includeInactive, size, cursor on search; nameContains, sort on the state list) at fault
             * @example name
             */
            field: string;
            /**
             * @description The catalog text with the arguments substituted
             * @example Name: Must not be blank
             */
            message: string;
        };
        Notice: {
            code: string;
            message: string;
        };
        /** @description RFC 9457 problem: the body of every error response. type, title, status, detail, code and args are always present; the other members only in the cases their descriptions name. */
        Problem: {
            /** @description The values substituted into the catalog text, as strings; empty when there are none */
            args: string[];
            /**
             * @description The catalog key, for example APP0400, DEM0502 or DEM1002
             * @example DEM1002
             */
            code: string;
            /** @description 409 DEM1002 only: the customer as now stored, including its version */
            current?: components["schemas"]["CustomerResponse"];
            /**
             * @description The catalog text of code with args substituted
             * @example Someone else changed record. Review data.
             */
            detail: string;
            /**
             * Format: uuid
             * @description 500 DEM9999 only: the correlation id, also written to the server's ERROR log line
             */
            errorId?: string;
            /** @description The fields at fault; the first entry receives focus. Present when the failure names a request property or parameter: 400 APP0400 on a body property or a path or query parameter, 400 DEM0007 on state, 422 DEM0501, DEM0502 or DEM0503 on the field whose rule failed, and 422 DEM9898 on addr, city, state and zip, in that order. Absent when it names none, as for a malformed body, an unknown property, content after the JSON value, an unknown route, 405, 406, 415, 401, 403, 404 DEM0599, 409, 502, 503 and 500 */
            errors?: components["schemas"]["FieldError"][];
            /**
             * Format: uri-reference
             * @description The request path; absent only when the path is not a usable URI reference
             * @example /api/customers/EEEF
             */
            instance?: string;
            /**
             * @description Failures of POST /api/customers/review only (422 and 502): the normalized State, present when the State rule passed before the failure and absent when the failure is at the State rule or before it
             * @example ME
             */
            stateAccepted?: string;
            /**
             * Format: int32
             * @description The HTTP status of the response
             * @example 409
             */
            status: number;
            /**
             * @description The HTTP reason phrase of status
             * @example Conflict
             */
            title: string;
            /**
             * Format: uri
             * @description urn:customer-master:problem: followed by the catalog key
             * @example urn:customer-master:problem:DEM1002
             */
            type: string;
        };
        ReviewRequest: {
            acctMgr?: string | null;
            acctPhone?: string | null;
            active?: string | null;
            addr?: string | null;
            city?: string | null;
            corpPhone?: string | null;
            name?: string | null;
            /** @enum {string} */
            purpose: "ADD" | "EDIT";
            state?: string | null;
            zip?: string | null;
        };
        ReviewResponse: {
            customer: WithRequired<components["schemas"]["CustomerFields"], "acctMgr" | "acctPhone" | "active" | "addr" | "city" | "corpPhone" | "name" | "state" | "zip">;
            notice: components["schemas"]["Notice"];
            standardized: boolean;
        };
        SearchResponse: {
            items: components["schemas"]["CustomerSummaryResponse"][];
            limitReached: boolean;
            nextCursor: string | null;
            notice: components["schemas"]["Notice"] | null;
        };
        SessionResponse: {
            roles: ("INQUIRY" | "MAINTENANCE")[];
            username: string;
        };
        StateResponse: {
            name: string;
            state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchCustomers: {
        parameters: {
            query?: {
                /** @description Name starts with (at most 13 characters) */
                name?: string;
                /** @description City starts with (at most 13 characters) */
                city?: string;
                /** @description Two-letter state code; blank = all */
                state?: string;
                /** @description Include inactive customers (F9) */
                includeInactive?: boolean;
                /** @description Page size 1–100, default 12 */
                size?: number;
                /** @description Opaque cursor from nextCursor */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of matching customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description APP0400 (cursor, size, lengths, U+0000) or DEM0007 (state) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerFields"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Path of the new customer, /api/customers/{custId} */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description APP0400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM1001 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (unsupported media type; Accept lists the supported type) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM0501, DEM0502, DEM0503 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0503 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reviewCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description All rules passed; confirm with DEM0000 (EDIT) or DEM0009 (ADD) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description APP0400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (unsupported media type; Accept lists the supported type) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM0501, DEM0502, DEM0503, DEM9898; errors names the fields at fault, and stateAccepted carries the normalized State when the State rule passed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0502; stateAccepted carries the normalized State when the State rule passed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 4-character base-36 customer id */
                custId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description APP0400 (id format) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM0599 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 4-character base-36 customer id */
                custId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdateRequest"];
            };
        };
        responses: {
            /** @description The stored customer with version + 1 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            /** @description APP0400 (including missing version) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM0599 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM1002 (stale version), whose current carries the customer as now stored, including its version; or DEM1001 (row locked), without current */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (unsupported media type; Accept lists the supported type) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM0501, DEM0502, DEM0503 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listStates: {
        parameters: {
            query?: {
                /** @description Case-insensitive name fragment, at most 10 characters */
                nameContains?: string;
                /** @description Order of the list: by name (default) or by code */
                sort?: "name" | "code";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"][];
                };
            };
            /** @description APP0400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (method not allowed; Allow lists the supported methods) */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description APP0400 (not acceptable) */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description DEM9999 (unexpected failure; errorId matches the server's ERROR log line) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
